The constant that breaks the iOS build
with this error message
CompileSwift normal x86_64 /Users/maia/workspace/maiatoday/urban-parakeet/iosApp/iosApp/ContentView.swift (in target 'iosApp' from project 'iosApp')
    cd /Users/maia/workspace/maiatoday/urban-parakeet/iosApp
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -c /Users/maia/workspace/maiatoday/urban-parakeet/iosApp/iosApp/iOSApp.swift -primary-file /Users/maia/workspace/maiatoday/urban-parakeet/iosApp/iosApp/ContentView.swift -emit-dependencies-path /Users/maia/workspace/maiatoday/urban-parakeet/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/Objects-normal/x86_64/ContentView.d -emit-reference-dependencies-path /Users/maia/workspace/maiatoday/urban-parakeet/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/Objects-normal/x86_64/ContentView.swiftdeps -serialize-diagnostics-path /Users/maia/workspace/maiatoday/urban-parakeet/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/Objects-normal/x86_64/ContentView.dia -target x86_64-apple-ios14.1-simulator -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.2.sdk -I /Users/maia/workspace/maiatoday/urban-parakeet/build/ios/Debug-iphonesimulator -F /Users/maia/workspace/maiatoday/urban-parakeet/build/ios/Debug-iphonesimulator -F /Users/maia/workspace/maiatoday/urban-parakeet/shared/build/cocoapods/framework -no-color-diagnostics -enable-testing -g -module-cache-path /Users/maia/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D DEBUG -serialize-debugging-options -enable-bare-slash-regex -empty-abi-descriptor -Xcc -working-directory -Xcc /Users/maia/workspace/maiatoday/urban-parakeet/iosApp -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift -enable-anonymous-context-mangled-names -Xcc -I/Users/maia/workspace/maiatoday/urban-parakeet/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/maia/workspace/maiatoday/urban-parakeet/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/My\ application-generated-files.hmap -Xcc -I/Users/maia/workspace/maiatoday/urban-parakeet/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/My\ application-own-target-headers.hmap -Xcc -I/Users/maia/workspace/maiatoday/urban-parakeet/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/My\ application-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/maia/workspace/maiatoday/urban-parakeet/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/maia/workspace/maiatoday/urban-parakeet/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/My\ application-project-headers.hmap -Xcc -I/Users/maia/workspace/maiatoday/urban-parakeet/build/ios/Debug-iphonesimulator/include -Xcc -I/Users/maia/workspace/maiatoday/urban-parakeet/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/DerivedSources-normal/x86_64 -Xcc -I/Users/maia/workspace/maiatoday/urban-parakeet/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/DerivedSources/x86_64 -Xcc -I/Users/maia/workspace/maiatoday/urban-parakeet/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/DerivedSources -Xcc -DDEBUG\=1 -Xcc -DCOCOAPODS\=1 -module-name My_application -frontend-parseable-output -disable-clang-spi -target-sdk-version 16.2 -o /Users/maia/workspace/maiatoday/urban-parakeet/build/ios/iosApp.build/Debug-iphonesimulator/iosApp.build/Objects-normal/x86_64/ContentView.o -index-unit-output-path /iosApp.build/Debug-iphonesimulator/iosApp.build/Objects-normal/x86_64/ContentView.o -index-store-path /Users/maia/Library/Developer/Xcode/DerivedData/iosApp-ehsyabccmskedydtitnysmzdcgyc/Index.noindex/DataStore -index-system-modules
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/shared.h"
        ^
/Users/maia/workspace/maiatoday/urban-parakeet/shared/build/cocoapods/framework/shared.framework/Headers/shared.h:155:37: error: expected member name or ';' after declaration specifiers
@property (class, readonly) int32_t SIZE_MAX __attribute__((swift_name("SIZE_MAX")));
                                    ^